name: Build

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
        
env:
  transfer: true
  release: true6
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        echo "${{ github.event.inputs.URL }}">url.txt
        sed -i s/ h/    h/g url.txt
        cat url.txt
        aria2c -x16 -j5 -s16 -U "netdisk;11.39.0;iPhone14ProMax;ios-iphone;16.2;zh_CN" --input-file=url.txt -d tmp || wget -U "netdisk;11.39.0;iPhone14ProMax;ios-iphone;16.2;zh_CN" -i url.txt -d tmp/

    - name: 检验和化分
      run: |
        if [[ $(du -sb tmp | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..." 
                  i=$(ls tmp)
                  split -d -b 2048m "tmp/$i" "tmp/$i"
                  rm -rf "tmp/$i"
                  fi    
                         
    - name: 上传到transfer
      if: env.transfer == 'true'      
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp
        i=$(ls tmp)     
        sudo ./transfer wet tmp/$i

    - name: 上传zhlhlf目录所有文件至 release
      if: env.release == 'true'      
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: tmp/*
        name: pack
        tag: pack--Android-${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
