name: Build

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: 'https://yun.daxiaamu.com/OnePlus_Roms/%E4%B8%80%E5%8A%A09R/ColorOS%2011.2%20A.08/LE2100domestic_11_A.08_2021052601230251.zip'
    
      name:
        description: 'URL'
        required: true
        default: 'update.zip'
        
env:
  transfer: true
  release: true6
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        aria2c -x16 -j5 -s16 -U "yimu" -d tmp "${{ github.event.inputs.URL }}" -o "${{ github.event.inputs.name }}" || wget -U "yimu" "${{ github.event.inputs.URL }}" -d tmp/

    - name: 检验并化分
      run: |
        
        if [[ $(du -sb tmp/${{ github.event.inputs.name }} | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - tmp/${{ github.event.inputs.name }} | split -d -b 2048m - tmp/${{ github.event.inputs.name }}
                  rm -rf tmp/${{ github.event.inputs.name }}        
              fi
              
    - name: 上传到transfer
      if: env.transfer == 'true'      
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp      
        sudo ./transfer wet tmp/*

    - name: 上传zhlhlf目录所有文件至 release
      if: env.release == 'true'      
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: tmp/*
        name: pack
        tag: pack--Android-${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
