name: Build

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: 'https://yun.daxiaamu.com/OnePlus_Roms/%E4%B8%80%E5%8A%A09R/ColorOS%2012.1%20C.29/LE2100_ColorOS%2012.1%20C.29_repack.zip'
        
env:
  transfer: true
  release: true6
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        aria2c -x16 -j5 -s16 -U "netdisk;11.34.5;20221102;android-android;12;JSbridge4.4.0;jointBridge;1.1.0;" -d tmp "${{ github.event.inputs.URL }}" -o "${{ github.event.inputs.name }}" || wget -U "yimu" "${{ github.event.inputs.URL }}" -d tmp/

    - name: 检验和化分
      run: |
        if [[ $(du -sb tmp | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..." 
                  i=$(ls tmp)
                  split -d -b 2048m "tmp/$i" "tmp/$i"
                  rm -rf "tmp/$i"
                  fi    
                         
    - name: 上传到transfer
      if: env.transfer == 'true'      
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp      
        sudo ./transfer wet tmp/*

    - name: 上传zhlhlf目录所有文件至 release
      if: env.release == 'true'      
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: tmp/*
        name: pack
        tag: pack--Android-${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
